- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/CLEANUP.md
- .github/ISSUE_TEMPLATE/ENHANCEMENT.md
- .github/ISSUE_TEMPLATE/SUPPORT.md
- .github/PULL_REQUEST_TEMPLATE.md
/kind flake
Add relevant issue and PR templates for subsequent repo management.
Fixes #none
none
```release-note
```
> flake: add PR template and issue template

- cmd/controller/main.go
- pkg/controllers/controllers.go
- pkg/controllers/providers/pricing/controllers.go
- pkg/providers/pricing/pricing.go
- pkg/utils/object/object.go
/kind feature
implement pricing
Fixes #
```release-note
```
> feat: add pricing

- Makefile
/kind flake
Now, the makefile has too much things we will not use temporarily, let's remove it.
Fixes #none
none
```release-note
```
> chore: simplify the makefile

- pkg/controllers/providers/instancetype/instancetype.go
- pkg/providers/instance/instance.go
- pkg/providers/instancetype/instancetype.go
/kind feature
add instancetype controller and instance provider add Create
Fixes #
```release-note
```
> feat: add instancetype controller and instance provider add Create

- hack/update-generated.sh
/kind cleanup
delete redundant content, the echo is not necessary
Fixes #none
none
```release-note
```
> cleanup: delete redundant content

- config/components/crds/karpenter.k8s.alicloud_ecsnodeclasses.yaml
- go.mod
- go.sum
- pkg/apis/v1alpha1/ecsnodeclass.go
- pkg/apis/v1alpha1/ecsnodeclass_status.go
- pkg/providers/vswitch/vswitch.go
/kind feature
Implement VSwitchProvider. *In AWS, it is SubnetProvider.*
Fixes https://github.com/cloudpilot-ai/karpenter-provider-alicloud/issues/12
Use `*ecs.DescribeInstancesResponseBodyInstances` as the` UpdateInflightIPs` parameter. https://github.com/cloudpilot-ai/karpenter-provider-alicloud/issues/12#issuecomment-2371070666
```release-note
```
> implement VSwitchProvider

- config/components/crds/karpenter.k8s.alicloud_ecsnodeclasses.yaml
- pkg/apis/v1alpha1/ecsnodeclass.go
- pkg/apis/v1alpha1/ecsnodeclass_status.go
- pkg/providers/securitygroup/securitygroup.go
/kind feature
Implement SecurityGroupProvider.
Fixes #
Alibaba Cloud security group has a limit on the number of IP addresses. 
```release-note
```
> implement SecurityGroupProvider

- go.mod
- go.sum
- pkg/operator/operator.go
- pkg/providers/pricing/pricing.go
- pkg/providers/pricing/pricing_test.go
/kind feature
feat: support price provider
Fixes https://github.com/cloudpilot-ai/karpenter-provider-alicloud/issues/8
none
```release-note
```
> feat: support price provider

- pkg/providers/launchtemplate/launchtemplate.go
- pkg/utils/utils.go
/kind feature
Implement part of the LaunchTemplateProvider.
`DeleteAll` and `InvalidateCache`.
Part of  https://github.com/cloudpilot-ai/karpenter-provider-alicloud/issues/9
`ResolveClusterCIDR(context.Context) error` method seems not necessary.
```release-note
```
> implement part of the LaunchTemplateProvider

- config/components/crds/karpenter.k8s.alicloud_ecsnodeclasses.yaml
- pkg/apis/v1alpha1/ecsnodeclass.go
- pkg/apis/v1alpha1/labels.go
- pkg/providers/imagefamily/aliyun3.go
- pkg/providers/imagefamily/custom.go
- pkg/providers/imagefamily/image.go
- pkg/providers/imagefamily/types.go
/kind feature
Implement ImageProvider. *In AWS, it is AMIProvider.*
Fixes #
```release-note
```
> implement ImageProvider

- go.mod
- pkg/cache/cache.go
- pkg/cache/unavailableofferings.go
- pkg/cache/unavailableofferings_test.go
- pkg/operator/options/options.go
- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/types.go
- pkg/utils/utils.go
/kind feature
instancetype add list
Fixes #
```release-note
```
> feat: instancetype add list

- pkg/apis/v1alpha1/ecsnodeclass.go
- pkg/controllers/controllers.go
- pkg/controllers/nodeclass/hash/controller.go
/kind feature
nodeclass add hash
Fixes #
```release-note
```
> feat: nodeclass add hash

- README.md
update banner picture size, make it look better
Fixes #none
none
```release-note
```
> doc: update banner picture size

- pkg/controllers/nodeclass/hash/controller.go
- pkg/controllers/nodeclass/termination/controller.go
- pkg/controllers/nodeclass/termination/events.go
/kind feature
nodeclass add termination
Fixes #
```release-note
```
> feat: nodeclass add termination

- pkg/cache/cache.go
- pkg/operator/operator.go
- pkg/providers/imagefamily/image.go
- pkg/providers/imagefamily/resolver.go
- pkg/providers/launchtemplate/launchtemplate.go
- pkg/providers/securitygroup/securitygroup.go
- pkg/utils/client/client.go
/kind feature
Added some providers to operator.
Fixes #
```release-note
```
> add provider to operator

- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/types.go
/kind cleanup
Fixes #
```release-note
```
> chore: fix zoneData

- cmd/controller/main.go
- config/components/crds/karpenter.k8s.alicloud_ecsnodeclasses.yaml
- go.mod
- pkg/apis/v1alpha1/ecsnodeclass.go
- pkg/apis/v1alpha1/ecsnodeclass_status.go
- pkg/cloudprovider/drift.go
- pkg/controllers/controllers.go
- pkg/controllers/nodeclass/status/controller.go
- pkg/controllers/nodeclass/status/securitygroup.go
- pkg/controllers/nodeclass/status/vswitch.go
- pkg/providers/instancetype/types.go
/kind bug
fix vswitch status
Fixes #
```release-note
```
> chore: fix vswitch status

- examples/nodepool/ecsnodeclass.yaml
- pkg/providers/instancetype/instancetype.go
/kind bug
fix: fix the bugs of nodeclaim creation
Fixes #none
none
```release-note
```
> fix: fix the bugs of nodeclaim creation

- cmd/controller/main.go
- pkg/apis/v1alpha1/ecsnodeclass_status.go
- pkg/controllers/controllers.go
- pkg/controllers/nodeclass/status/controller.go
- pkg/controllers/nodeclass/status/image.go
- pkg/providers/instance/instance.go
/kind bug
fix: fix some bugs of node creation
Fixes #none
fix: fix some bugs of node creation
```release-note
```
> fix: fix some bugs of node creation

- pkg/providers/instance/instance.go
- pkg/providers/instance/types.go
/kind bug
fix status
Fixes #
```release-note
```
> fix status

- pkg/providers/ack/ack.go
/kind feature
feat: add startup taint which karpenter ask for
Fixes #none
none
```release-note
```
> feat: add startup taint which karpenter asks for

- pkg/providers/instance/instance.go
/kind bug
fix instance List
Fixes #
```release-note
```
> fix: fix instance List

- examples/nodepool/ecsnodeclass.yaml
- examples/nodepool/nodepool.yaml
- pkg/apis/v1alpha1/ecsnodeclass.go
- pkg/providers/ack/ack.go
- pkg/providers/instance/instance.go
- pkg/providers/instancetype/types.go
/kind bug
fix: enable node deletion when the pod is empty
Fixes #none
fix: enable node deletion when the pod is empty
```release-note
```
> fix: enable node deletion when the pod is empty

- examples/nodepool/nodepool.yaml
- pkg/controllers/nodeclass/status/controller.go
- pkg/controllers/nodeclass/status/securitygroup.go
- pkg/controllers/nodeclass/status/vswitch.go
/kind bug
fix: re-reconcile the nodeclass status
Fixes #none
none
```release-note
```
> fix: re-reconcile the nodeclass status

- pkg/providers/ack/ack.go
- pkg/providers/ack/ack_test.go
/kind cleanup
cleanup: make resolve nodeconfig logic better
Fixes #none
none
```release-note
```
> cleanup: make resolve nodeconfig logic better

- pkg/providers/instance/instance.go
- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/types.go
/kind bug
fix NextToken and filter nil IntanceType
Fixes #
```release-note
```
> fix: fix NextToken and filter nil IntanceType

- pkg/operator/operator.go
- pkg/operator/options/options.go
- pkg/operator/options/options_validation.go
- pkg/providers/instance/instance.go
- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/types.go
/kind bug
fix: fix instance type selection that does not match terway cni
Fixes #none
https://help.aliyun.com/zh/ack/ack-managed-and-ack-dedicated/user-guide/container-network/?spm=a2c4g.11186623.help-menu-85222.d_2_4_3.6d501109uQI315&scm=20140722.H_195424._.OR_help-V_1
```release-note
```
> fix: fix instance type selection that does not match terway cni

- pkg/cloudprovider/cloudprovider.go
/kind cleanup
When delete the intances, sometimes we could not get it because it's deleted, and there will be a error log; let's remove it.
Fixes #none
```release-note
```
> cleanup: delete some unnecessary error log

- pkg/providers/instance/instance.go
/kind bug
add judge launchInstance nil
Fixes #
```release-note
```
> fix: add judge launchInstance nil

- pkg/apis/v1alpha1/labels.go
- pkg/providers/instancetype/types.go
/kind feature
feat: support instance family selection
Fixes #
```release-note
```
> feat: support instance family selection

- .github/workflows/latest-build.yaml
- .ko.yaml
/kind feature
add ci to push the latest image build
Fixes #
```release-note
```
> ci: add ci for latest image build, and push

- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/types.go
> feat: support flannel cni

- cmd/controller/main.go
- pkg/cache/unavailableofferings.go
- pkg/controllers/controllers.go
- pkg/controllers/interruption/controller.go
- pkg/controllers/interruption/events/events.go
- pkg/operator/operator.go
- pkg/operator/options/options.go
- pkg/providers/instance/instance.go
- pkg/providers/instancetype/instancetype.go
/kind feature
support interruption and v1 replace v1beta1
Fixes #
```release-note
```
> feat: support interruption and karpenter api v1 replace v1beta1

- pkg/controllers/interruption/controller.go
/kind bug
fix interruption
Fixes #
```release-note
```
> fix: fix interruption

- pkg/controllers/nodeclaim/garbagecollection/controller.go
- pkg/providers/instance/instance.go
- pkg/providers/instance/types.go
- pkg/utils/alierrors/errors.go
/kind cleanup
cleanup: ignore some unnecessary error
Fixes #
```release-note
```
> cleanup: ignore some unnecessary error

- pkg/apis/v1alpha1/labels.go
- pkg/controllers/nodeclaim/tagging/controller.go
- pkg/operator/options/options.go
- pkg/operator/options/options_validation.go
- pkg/providers/instance/instance.go
/kind cleanup
The alibaba cloud cluster name can be modified, if it is modified, it will cause a lot of problems, so we abandon the use of cluster-name
Fixes #
```release-note
```
> cleanup: remove cluster-name

- pkg/providers/instancetype/types.go
/kind bug
fix: fix node selection with flannel cni
Fixes #none
```release-note
```
> fix: fix node selection with flannel cni

- pkg/operator/options/options.go
- pkg/providers/instancetype/types.go
/kind bug
fix: fix the overhead calculation
Fixes #none
fix: fix the overhead calculation
```release-note
```
> fix: fix the overhead calculation

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/CLEANUP.md
- .github/ISSUE_TEMPLATE/ENHANCEMENT.md
- .github/ISSUE_TEMPLATE/SUPPORT.md
- config/components/crds/karpenter.sh_nodeclaims.yaml
- config/components/crds/karpenter.sh_nodepools.yaml
- examples/nodepool/nodepool.yaml
- pkg/apis/v1alpha1/labels.go
/kind cleanup
alibabacloud replace alicloud
Fixes #
```release-note
```
> cleanup: alibabacloud replace alicloud

- pkg/providers/ack/ack.go
The requirement details is here:
[Detect the cni automatically](https://github.com/cloudpilot-ai/karpenter-provider-alicloud/issues/91)
Fixes #[Detect the cni automatically](https://github.com/cloudpilot-ai/karpenter-provider-alicloud/issues/91)
```release-note
```
> support to detect cni automatically

- pkg/operator/operator.go
/kind bug
instancetype.NewDefaultProvider fix ackProvider nil 
Fixes #
```release-note
```
> fix: instancetype.NewDefaultProvider fix ackProvider nil 

- Makefile
/kind cleanup
sync defaultMinimumVersion
Fixes #
```release-note
```
> cleanup: sync defaultMinimumVersion

- examples/nodepool/ecsnodeclass.yaml
/kind cleanup
Fixes #
```release-note
```
> chore: change example nodeclass os

- pkg/providers/instance/instance.go
- pkg/providers/instancetype/types.go
/kind bug
Fixes #none
```release-note
```
> fix: report error if image not found

- Makefile
> fix helm install failed if ns doesn't be created beforehand

- pkg/providers/instancetype/types.go
/kind bug
fix: fix gpu node label
Fixes #none
```release-note
```
> fix: fix gpu node label

- pkg/controllers/nodeclaim/garbagecollection/controller.go
- pkg/providers/instancetype/instancetype.go
/kind bug
Fixes #
```release-note
```
> fix: fix capacity limitation

- pkg/providers/instancetype/types.go
/kind bug
fix info nil
Fixes #
```release-note
```
> fix info nil

- pkg/providers/imagefamily/resolver.go
/kind bug
parallel get disk information
Fixes #
improve performance
```release-note
```
> fix: parallel get intancetype disk information

- .github/workflows/publish-charts.yaml
- charts/README.md
- charts/karpenter/templates/deployment.yaml
- charts/karpenter/values.yaml
/kind cleanup
Fixes #
```release-note
```
> ci: add gh pages workflow

- charts/karpenter/crds/karpenter.k8s.alibabacloud_ecsnodeclasses.yaml
- examples/nodepool/ecsnodeclass.yaml
- pkg/apis/v1alpha1/ecsnodeclass.go
- pkg/providers/imagefamily/resolver.go
- pkg/providers/instance/instance.go
/kind bug
fix: fix disk configuration
Fixes #none
```release-note
```
> fix: fix disk configuration

- charts/karpenter/crds/karpenter.k8s.alibabacloud_ecsnodeclasses.yaml
- pkg/apis/v1alpha1/ecsnodeclass.go
- pkg/apis/v1alpha1/zz_generated.deepcopy.go
/kind cleanup
Fixes #
```release-note
```
> cleaup: clean unsupported field

- pkg/apis/v1alpha1/ecsnodeclass.go
- pkg/providers/instance/instance.go
/kind bug
disk need support PerformanceLevel
Fixes #71 
```release-note
```
> add performance level for system disk

- pkg/apis/v1alpha1/ecsnodeclass.go
- pkg/providers/instance/instance.go
/kind feature
add resource group id
Fixes #
```release-note
```
> add resource group id

- pkg/providers/instance/instance.go
/kind bug
fix: check node creation result
Fixes #
```release-note
```
> fix: check node creation result

- pkg/providers/ack/ack.go
- pkg/providers/imagefamily/image.go
- pkg/providers/imagefamily/resolver.go
- pkg/providers/instance/instance.go
- pkg/providers/instancetype/instancetype.go
- pkg/providers/securitygroup/securitygroup.go
- pkg/providers/vswitch/vswitch.go
- pkg/utils/alierrors/errors.go
/kind cleanup
err add requestId
Fixes #
```release-note
```
> cleanup: err add requestId

- pkg/providers/instance/instance.go
/kind feature
instance use cache
Fixes #
```release-note
```
> feat: instance use cache

- README.md
> doc: Make description better

- charts/karpenter/crds/karpenter.k8s.alibabacloud_ecsnodeclasses.yaml
- go.mod
- pkg/apis/v1alpha1/ecsnodeclass.go
- pkg/controllers/controllers.go
- pkg/controllers/nodeclaim/unregisteredtaint/controller.go
- pkg/operator/operator.go
- pkg/operator/options/options.go
- pkg/providers/instance/instance.go
/kind feature
fix the exception when scale 100+ or more ecs.
Fixes #
```release-note
```
> feat: fix the exception when scale 100+ or more ecs.

- pkg/operator/operator.go
/kind feature
feat: support pvc zone label
Fixes #137 
```release-note
```
> feat: support pvc zone label

- pkg/operator/operator.go
/kind bug
Fixes #
```release-note
```
> fix: fix csi topology scheduling

- .github/workflows/release-build.yaml
/kind flake
ci: add release image build
Fixes #none
```release-note
```
> ci: add release image build

- pkg/providers/instance/instance.go
/kind cleanup
chore: add tag to apg to enhance the SLA
AlibabaCloud will monitor based on the tag, to enhance the SLA of this API
Fixes #none
none
```release-note
```
> chore: add tag to apg to enhance the SLA

- pkg/providers/version/version.go
/kind cleanup
typo: fix typo
Fixes #none
typo: fix typo
```release-note
```
> typo: fix typo

- charts/karpenter/templates/deployment.yaml
- charts/karpenter/values.yaml
Add one of the following kinds:
/kind feature
Fixes #161 
user can customize node selection for karpenter pod using this enhancement.
> add nodeSelector for karpenter node selection

- pkg/providers/instance/instance.go
/kind bug
handle vswitch not found case in getProvisioningGroup
Fixes #
```release-note
```
> chore: handle vswitch not found case in getProvisioningGroup

- pkg/providers/instance/instance.go
Fixes #
```release-note
Fix: Do not throw an error when some instance types are unavailable for certain vSwitches.
```
> cherry-pick: handle vswitch not found case in getProvisioningGroup

- .github/workflows/latest-build.yaml
- .github/workflows/release-build.yaml
- charts/karpenter/values.yaml
/kind cleanup
push images to acr to avoid pulling image error
Fixes #
```release-note
```
> ci: push images to acr

- pkg/providers/instance/instance.go
> chore: print error beautiful

- pkg/providers/ack/ack.go
The pr is trying to refactor the code for readability and clarity.
/kind cleanup
```release-note
```
> refactor parsing userData

- pkg/operator/operator.go
- pkg/providers/instancetype/instancetype.go
/kind cleanup
chore: delete redundant function parameters
Fixes #none
chore: delete redundant function parameters
```release-note
```
> chore: delete redundant function parameters

- pkg/apis/v1alpha1/ecsnodeclass_status.go
- pkg/controllers/nodeclass/status/controller.go
/kind cleanup
chore: cleanup duplicated nodeclass status
Fixes #none
none
```release-note
```
> chore: cleanup duplicated nodeclass status

- charts/karpenter/crds/karpenter.sh_nodeclaims.yaml
- charts/karpenter/crds/karpenter.sh_nodepools.yaml
- hack/update-generated.sh
/kind cleanup
chore: auto generate nodepool and nodeclaim crds
Fixes #none
none
```release-note
```
> chore: auto generate nodepool and nodeclaim crds

- OWNERS
@daimaxiaxie and @helen-frank have contributed a lot to this project. I nominate them to be approvers.
Fixes #none
none
```release-note
```
> doc: nominate helen-frank/daimaxiaxie as approver

- pkg/operator/operator.go
- pkg/providers/instance/instance.go
…nce with no available resources
/kind flake
Avoiding duplicate requests for unavailable instances
Fixes #
```release-note
update unavailableOfferings when adding a launchInstance with no available resources
```
> feat: update unavailableOfferings when adding a launchInstance with no available resources

- pkg/controllers/nodeclass/volumesize/controller.go
/kind bug
Fixes #
```release-note
```
> fix: fix nil pointer of disk conversation

- pkg/operator/operator.go
- pkg/providers/instance/instance.go
/kind feature
https://github.com/cloudpilot-ai/karpenter-provider-alibabacloud/pull/197
Fixes #
```release-note
```
> Cherry pick PR(197)/feat: update unavailableOfferings when adding a launchInstance with no available resources

- pkg/providers/instancetype/instancetype.go
> cherry-pick: fix: allow ClosedWithStock capacity type

- pkg/providers/instancetype/instancetype.go
> fix: consider vs zones when creating types offerings

- NOTICE
doc: add notice file for restrictions
Fixes #none
doc: add notice file for restrictions
```release-note
```
> doc: add notice file for restrictions

- charts/karpenter/crds/karpenter.k8s.alibabacloud_ecsnodeclasses.yaml
- pkg/apis/v1alpha1/ecsnodeclass.go
- pkg/providers/ack/ack.go
- pkg/providers/instance/instance.go
/kind feature
Fixes #
```release-note
support custom userdata when create node
```
> feat: support custom userData

- pkg/providers/ack/ack.go
/kind bug
replace the runtime configurations of the attach script
Fixes #
```release-note
NONE
```
> fix: replace the attach-script's runtime configurations

- ADOPTERS.md
doc: add adopters
Fixes #none
doc: add adopters
```release-note
```
> doc: add adopters

- pkg/apis/v1alpha1/ecsnodeclass.go
/kind bug
fix family lowercase.
Fixes #
```release-note
None
```
> fix family lowercase

- pkg/providers/instance/instance.go
/kind bug
fix ice err
Fixes #
```release-note
```
> fix(instance): ice err

- pkg/providers/instance/instance.go
/kind bug
fix instance ice err
Fixes #
```release-note
```
> cherry-pick: fix instance ice err

- pkg/apis/v1alpha1/labels.go
- pkg/providers/instancetype/types.go
/kind feature
Add aliyun/eni into ecs instance type info and support aliyun/eni resource request in pod
Fixes #159 
```release-note
```
> support request aliyun/eni
