cloudpilot-ai/karpenter-provider-alibabacloud

go.mod
pkg/providers/instancetype/instancetype.go

/kind feature
instancetype implement UpdateInstanceTypes and UpdateInstanceTypeOfferings
Fixes #
```release-note
```

feat: instancetype implement UpdateInstanceTypes and UpdateInstanceTypeOfferings

---

config/config.go
pkg/cloudprovider/cloudprovider.go
pkg/providers/instance/instance.go
pkg/providers/instance/types.go
pkg/providers/instancetype/instancetype.go
pkg/utils/utils.go

/kind feature
implement cloudprovider Get and List
Fixes #
```release-note
```

feat: implement cloudprovider Get and List

---

cmd/controller/main.go
go.mod
pkg/controllers/controllers.go
pkg/controllers/nodeclaim/garbagecollection/controller.go
pkg/controllers/nodeclaim/tagging/controller.go
vendor/github.com/awslabs/operatorpkg/reasonable/reasonable.go
vendor/modules.txt

/kind feature
nodeclaim add controller garbagecollection and tagging
Fixes #
```release-note
```

feat: nodeclaim add controller garbagecollection and tagging

---

pkg/apis/v1alpha1/ecsnodeclass.go
pkg/providers/instancetype/types.go

/kind bug
fix NetworkEncryptionSupport nil
Fixes #
```release-note
```

fix:  NetworkEncryptionSupport nil

---

pkg/controllers/nodeclass/status/controller.go

/kind bug
Update the AddFinalizer operation to modify the nodeClass object directly instead of the stored copy. This change maintains the correct patch operation flow while making the code's intention clearer.
The stored copy should remain unmodified as it serves as the base state for calculating the patch difference, while nodeClass should receive the actual modifications.
Fixes #78 
NONE

fix(nodeclass): update finalizer operation target in status controller

---

pkg/operator/operator.go
pkg/operator/options/options.go
pkg/operator/options/options_validation.go
pkg/providers/ack/ack.go
pkg/providers/instancetype/instancetype.go

/kind feature
chore: use ack provider to resolve the cluster cni
Fixes #91
```release-note
```

chore: use ack provider to resolve the cluster cni

---

pkg/operator/operator.go
pkg/providers/instance/instance.go
pkg/providers/vswitch/vswitch.go

/kind bug
For HZ region, there will be follow error:
```
{"level":"ERROR","time":"2024-11-13T10:12:18.197Z","logger":"controller","message":"Reconciler error","commit":"f2ed819","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.alibabacloud","controllerKind":"ECSNodeClass","ECSNodeClass":{"name":"defaultnodeclass"},"namespace":"","name":"defaultnodeclass","reconcileID":"9218c561-f101-4056-ae3a-85bb458fba42","error":"getting vSwitches, describing vSwitches {\"tags\":{\"karpenter.sh/discovery\":\"ack-alert-poc\"}}, SDKError:\n   StatusCode: 400\n   Code: MissingParameter\n   Message: code: 400, The input parameter \"regionId or vpcInstanceId\" that is mandatory for processing this request is not supplied. request id: AA9C3358-902E-5ECC-BA6C-C799936E4411\n   Data: …
```

fix: describe vsw with region para

---

charts/karpenter/templates/poddisruptionbudget.yaml
charts/karpenter/values.yaml
pkg/cache/cache.go
pkg/cloudprovider/drift.go
pkg/cloudprovider/events/events.go
pkg/controllers/controllers.go
pkg/controllers/interruption/controller.go
pkg/controllers/nodeclass/status/securitygroup.go
pkg/operator/options/options_validation.go
pkg/providers/instancetype/instancetype.go
pkg/providers/instancetype/types.go
pkg/providers/vswitch/vswitch.go

/kind cleanup
Fixes #
```release-note
```

cleanup: fix problems

---

pkg/cache/cache.go
pkg/operator/operator.go
pkg/providers/ack/ack.go

/kind feature
[Feat #71](https://github.com/cloudpilot-ai/karpenter-provider-alibabacloud/issues/71)

feat: cache cluster attach script

---

pkg/providers/ack/ack.go
pkg/providers/instance/instance.go

add taints for node

---

pkg/providers/instancetype/instancetype.go
pkg/providers/instancetype/types.go

/kind bug
referring to https://help.aliyun.com/zh/ack/ack-managed-and-ack-dedicated/user-guide/resource-reservation-policy#0f5ffe176df7q
Caculate the overhead correctly
Fixes #none
none
```release-note
```

fix: calculate the overhead correctly

---

pkg/providers/instance/instance.go

/kind cleanup
remove the todo, the bug is fixed by alibabacloud
Fixes #
```release-note
```

chore: use SecurityGroupIds instad of SecurityGroupId for ProvisionGroup

---

pkg/providers/imagefamily/image.go

/kind bug
Sometimes, alibabacloud will update the image to a newer version. If we do not use showExpired para, we clould not resolve the images.
This only happen when the user specify the image id
Fixes #
none
```release-note
```

fix: get image status even it's expired

---

charts/karpenter/crds/karpenter.k8s.alibabacloud_ecsnodeclasses.yaml
pkg/apis/v1alpha1/ecsnodeclass.go

/kind bug
If users only set disk size, the categories will be empty, which is not correct
Fixes #none
```release-note
```

fix: set default disk categories and size

---

pkg/providers/instancetype/instancetype.go
pkg/providers/instancetype/types.go

Fixes #
```release-note
Fix: Resolve spot capacity correctly. Sometimes, on-demand resources are out of capacity, but spot instances still have available capacity
```

fix: resolve spot capacity correctly

---

pkg/providers/instancetype/instancetype.go
pkg/providers/instancetype/types.go

Fixes #
```release-note
Fix: Resolve spot capacity correctly. Sometimes, on-demand resources are out of capacity, but spot instances still have available capacity
```

cherry-pick: resolve spot capacity correctly

---

pkg/providers/ack/ack.go

/kind bug
We encountered a situation where the `DescribeClusterAttachScriptsRequest` will **use the default nodepool when the NodepoolID is not provided**. However, in some cases, the default nodepool may have been deleted, but `DescribeClusterAttachScriptsRequest` will still use the CRI configuration of the default nodepool. In an ACK cluster with version 1.24, if the default nodepool was originally created with Docker Runtime but was later deleted and replaced with a new nodepool using Containerd Runtime, this could cause nodes to fail to register to the cluster. This is because Docker Runtime only supports clusters of version 1.22 and below now.
Fixes #
```release-note
To call `DescribeClusterAttachScriptsRequest`, Karpenter need to provide the NodePoolID now, preferably selecting the …
```

fix: select nodepool id when describe cluster attach scripts

---

charts/karpenter/templates/deployment.yaml
charts/karpenter/templates/role.yaml
charts/karpenter/values.yaml
pkg/providers/ack/ack.go

/kind cleanup
cherry pick the commits to release branch
Fixes #
```release-note
NONE
```

cherry-pick: unused env and select nodepool ID

---

charts/karpenter/crds/karpenter.k8s.alibabacloud_ecsnodeclasses.yaml
pkg/apis/v1alpha1/ecsnodeclass.go
pkg/providers/instance/instance.go

/kind feature
support set password and key pair in ecs node class.
Fixes #148 
```release-note
ecsnodeclass: support set password and key pair in ecs node class.
```

support set password and key pair in ecs node class

---

charts/karpenter/crds/karpenter.k8s.alibabacloud_ecsnodeclasses.yaml
pkg/apis/v1alpha1/ecsnodeclass.go
pkg/providers/cluster/ackmanaged.go
pkg/providers/cluster/custom.go
pkg/providers/cluster/types.go
pkg/providers/instance/instance.go

/kind feature
Fixes #228
```release-note
Support adding data disks for storing container data and images
```

feat: Support add data disks for storing container data and images

---

charts/karpenter/crds/karpenter.k8s.alibabacloud_ecsnodeclasses.yaml

/kind bug
ECSNodeClass cannot be created successfully when AlibabaCloudLinux3 or ContainerOS is specified, but it can be created successfully when AlibabaCloudLinux3@latest is used, but karpenter throws the error: "unsupported image family AlibabaCloudLinux3@latest"
Fixes #
```release-note
action required
```

fix imageSelectorTerms must match family format
